name: rebirth_2048
description: A biological evolution and ecological revival game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/creatures/chapter_01_ocean/
    - assets/creatures/chapter_02_land/
    - assets/creatures/chapter_03_sky/
    - assets/backgrounds/chapter_01_ocean/
    - assets/backgrounds/chapter_02_land/
    - assets/backgrounds/chapter_03_sky/
    - assets/creatures/chapter_04_history/
    - assets/backgrounds/chapter_04_history/
    - assets/creatures/chapter_05_modern_world/
    - assets/backgrounds/chapter_05_tech/
    - assets/creatures/chapter_06_universe/
    - assets/backgrounds/chapter_06_universe/
