// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18lNBCUmSCGb27LIvNdTBObvWx7fK4Kk',
    appId: '1:980968758380:web:8cf25d69944cb4e9b08c49',
    messagingSenderId: '980968758380',
    projectId: 'rebirth-2048',
    authDomain: 'rebirth-2048.firebaseapp.com',
    storageBucket: 'rebirth-2048.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtcVzQYyO8BDUE00EeGcbF_LYFZsvdBzM',
    appId: '1:980968758380:android:bbc653501aa72128b08c49',
    messagingSenderId: '980968758380',
    projectId: 'rebirth-2048',
    storageBucket: 'rebirth-2048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRFWOUDv_wQnETX7Zy17Kegi2RFCrYo0',
    appId: '1:980968758380:ios:79289498378609cfb08c49',
    messagingSenderId: '980968758380',
    projectId: 'rebirth-2048',
    storageBucket: 'rebirth-2048.firebasestorage.app',
    iosBundleId: 'com.example.rebirth2048',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrRFWOUDv_wQnETX7Zy17Kegi2RFCrYo0',
    appId: '1:980968758380:ios:79289498378609cfb08c49',
    messagingSenderId: '980968758380',
    projectId: 'rebirth-2048',
    storageBucket: 'rebirth-2048.firebasestorage.app',
    iosBundleId: 'com.example.rebirth2048',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB18lNBCUmSCGb27LIvNdTBObvWx7fK4Kk',
    appId: '1:980968758380:web:61a4138f2c69eca0b08c49',
    messagingSenderId: '980968758380',
    projectId: 'rebirth-2048',
    authDomain: 'rebirth-2048.firebaseapp.com',
    storageBucket: 'rebirth-2048.firebasestorage.app',
  );
}
